---
- hosts: all
  sudo: true
  roles:
  tasks:
  - name: Ansible alive
    debug: msg="I am alive, let's build TKMON"
  - name: Install packages
    apt: pkg={{item}} state=installed update_cache=no
    with_items:
    - software-properties-common
    - apache2
    - apache2-mpm-event
    - libapache2-mod-fastcgi
    - php5
    - php5-cli
    - php5-sqlite
    - php5-fpm
    - php5-curl
    - php5-xcache
    - php5-xdebug
    - php-pear
    - pnp4nagios
    - python-setuptools
  - name: Test launchpad repository
    stat: path=/etc/apt/sources.list.d/formorer-icinga-trusty.list
    register: sr
  - name: Add icinga launchpad
    command: apt-add-repository --yes ppa:formorer/icinga
    when: sr.stat.md5 is not defined
  - name: Install packages 2
    apt: pkg={{item}} state=installed update_cache=yes
    with_items:
    - icinga
    - icinga-cgi
    - icinga-cgi-bin
    - icinga-common
    - icinga-core
    - postfix
    - ntp
  - name: Test PHPUNIT
    stat: path=/usr/local/bin/phpunit
    register: sp
  - name: Download phpunit
    command: 'wget
              https://phar.phpunit.de/phpunit.phar
              -O /usr/local/bin/phpunit.phar'
    when: sp.stat.md5 is not defined
  - name: Rename PHPUNIT
    command: 'mv /usr/local/bin/phpunit.phar /usr/local/bin/phpunit'
    when: sp.stat.md5 is not defined
  - name: chmod PHPUNIT
    command: 'chmod 0755 /usr/local/bin/phpunit'
    when: sp.stat.md5 is not defined
  - name: Configure XCache
    copy: 'src=files/php5/xcache.ini
          dest=/etc/php5/mods-available/xcache.ini
          mode=0644'
  - name: Configure PHP
    copy: 'src=files/php5/php.ini
          dest=/etc/php5/fpm/php.ini
          mode=0644'
  - name: Configure sp.php5-fpm
    copy: 'src=files/php5-fpm/www.conf
          dest=/etc/php5/fpm/pool.d/www.conf
          backup=yes
          mode=0644'
  - name: Restart php5-fpm
    command: /sbin/restart php5-fpm
  - name: Enable apache2 module rewrite
    apache2_module: name=rewrite state=present
  - name: Enable apache2 moduls
    apache2_module: name={{item}} state=present
    with_items:
    - rewrite
    - fastcgi
    - actions
  - name : FastCGI jail
    file: 'path=/var/www/cgi-bin/
          mode=0755
          owner=www-data
          group=www-data
          state=directory'
  - name: Configure apache2 fastcgi
    copy: 'src=files/apache2/fastcgi.conf
          dest=/etc/apache2/mods-available/fastcgi.conf
          backup=yes
          mode=0644'
  - name: Configure apache2 ports
    copy: 'src=files/apache2/ports.conf
          dest=/etc/apache2/ports.conf
          backup=yes
          mode=0644'
  - name: TKMON apache2 configuration 1
    copy: 'src=../../etc/apache2/conf.d/tkmon.conf
          dest=/etc/apache2/conf-available/tkmon.conf
          mode=0644'
  - name: PNP4Nagios Apache configuration
    copy: 'src=files/pnp4nagios/apache.conf
          dest=/etc/apache2/conf-available/pnp4nagios.conf
          mode=0644'
  - name: Apache2 enable conf
    command: /usr/sbin/a2enconf {{item}}
    with_items:
    - tkmon
    - pnp4nagios
  - name: Icinga htpass file
    copy: 'src=files/icinga/htpasswd.users
          dest=/etc/icinga/htpasswd.users
          owner=www-data
          group=www-data
          mode=0640'
  - name: TKMON group
    group: name=tkmonweb state=present system=yes
  - name: Copy sudoers
    copy: 'src=../../etc/sudoers.d/tkmon
          dest=/etc/sudoers.d/tkmon
          mode=0440'
  - name: WWW User granted tkmon rights
    user: name=www-data groups=tkmonweb append=yes
  - name: Restart apache2
    service: name=apache2 state=restarted
  - name: Icinga icinga.cfg
    copy: 'src=files/icinga/icinga.cfg
          dest=/etc/icinga/icinga.cfg
          mode=0644'
  - name: Icinga cgi.cfg
    copy: 'src=files/icinga/cgi.cfg
          dest=/etc/icinga/cgi.cfg
          mode=0644'
  - name: Icinga tkmon base config
    copy: 'src=../../etc/icinga/
          dest=/etc/icinga/tkmon'
  - name: Config owner
    command: chown -R 33.33 /etc/icinga/tkmon
  - name: Restart icinga
    service: name=icinga state=restarted
  - name: Copy update script
    copy: 'src=../../bin/async_update.py
          dest=/usr/local/sbin/async_update.py
          mode=0755
          owner=root
          group=root'
  - name: Enable NPCD
    copy: 'src=files/pnp4nagios/npcd
          dest=/etc/default/npcd
          mode=0644'
  - name: Restart npcd
    service: name=npcd state=restarted
  - name: Test TKLAERT
    stat: path=/usr/local/bin/tkalert
    register: st
  - name: Install TKALERT
    shell: 'cd /vagrant/contrib/tkalert; /usr/bin/env python setup.py install'
    when: st.stat.md5 is not defined